### PR TITLE
Bug fixes and code improvements for WP-GITM:

### PR DESCRIPTION
**Pull request by xingmengx**
1. Fixed IsForbiddenFreq bug in user.f90, so IsForbiddenFreq is set on all processors.
2. Fixed error handling for #USEBCPERTURBATION in set_inputs.f90.
3. Improved sub-array passing for the lower boundary condition.
4. Improved get_mean_bcs to include the geometry effect.
5. Updated reference solutions for WP-GITM tests;
   Added column explanation for imf data files provided for WP-GITM tests.

### CODE REVIEW

**Comment by aaronjridley** [comment]
Hey Xing - thanks for this.  I am terribly sorry that this has taken so long to actually get to.  It has been a hard semester so far.  Yesterday I spent the day cleaning up GITM.  There are two things that I worked on mainly: (1) getting things out of advance, and (2) getting things out of calc_sources.  I moved the get_mean_bcs out of advance and into the user file. I wasn't exactly sure where I should move this, but it seemed like the right place. Could you modify your code so that it is consistent with what I did?  I am not sure what the best way of doing this is.  Actually, it looks like the only thing that we would really have to worry about is in advance and user. Probably if you took the code out of advance and put it in user.f90, maybe it would not have a conflict? Let me know what you think.

**Comment by xingmengx** [comment]
Hi Aaron -- That is totally fine. Thank you so much for doing this. Of course, I can modify my code. Let me resolve the conflict. I think user.f90 is a good place for get_mean_bcs.

**Comment by xingmengx** [comment]
Hi Aaron -- I resolved the conflict. Could you merge the pull request? 

There is a risk that the changes I made in get_mean_bcs (was in advance.f90, now is in user.f90) will vanish, because you moved an older version of get_mean_bcs to user.f90. I don't know if Git is clever enough to capture this. If not, I will create another pull request after you merge this pull request.

**Comment by xingmengx** [comment]
Hi Aaron -- I think I resolved the conflict. I brought my fork up to date with the latest GITM you have. Could you merge this pull request before you make further changes to GITM? I hope it will work. After you merge it, I will double check the code to make sure my changes are still there. I will do a test run as well.

**Review by aaronjridley — APPROVED** [review]
Looks good!

**Pull request merged**
