### PR TITLE
WP-GITM

### PR DESCRIPTION
**Pull request by xingmengx**
Aaron, here is the code with WP added, along with two tests and a manual.

### CODE REVIEW

**Comment by aaronjridley** [comment]
Hi Xing - sorry that it has taken me so long to do this!!!  The only real issue that I have with this is in advance.f90.  Could you follow the style of the other lower boundary perturbations and simply do a call to do the averages and such, leaving advance to be more streamlined?  For example, you could make a subroutine that is called update_userbcperturbation and call that right after the waccm check (i.e.,   if (UseBcPerturbation) then call update_userbcperturbation). 

You may also want to put in the date that you have committed the files that you have copyrighted.  I don't find that too interesting, but many people like to put in something like REVISION HISTORY: Initial version: April 2, 2021, or something.  Clearly, you don't have to do that if you don't want. (The copyright statement says 2021, so that should be fine, but if you want more detail later.....)

Otherwise, these changes look fine.  There are some style things, like spaces and such, but I don't tend to care too much about those....

Thanks for doing it this way!!!  I think that when you address the advance thing, just let me know and I will approve.

**Comment by xingmengx** [comment]
Hi Aaron - That's totally fine. Thank you for reviewing. I have added a new subroutine get_mean_bcs in advance.f90. Let me know if you prefer a different place to put the new subroutine. I also added revision history.

**Review by aaronjridley — APPROVED** [review]
Very nice changes.  Thanks for doing this Xing!

**Comment by aaronjridley** [comment]
Go ahead and merge the pull request, Xing.  Thanks for doing it like this! You are awesome!

**Comment by xingmengx** [comment]
No problem. Thank you Aaron!

**Pull request merged**
